### ISSUE TITLE
Rename Brainfuck.b to Brainfuck.bf

### ISSUE THREAD

**Issue by calgary34** [clarkzjw/one-two-three...infinity#53]
[The Hello World project](https://github.com/leachim6/hello-world/blob/master/b/Brainfuck.bf) uses it.

**Comment by clarkzjw** [comment]
Actually, I think both `.b` and `.bf` extensions are used widely, see https://esolangs.org/wiki/Brainfuck as well. I think I will not rename it, but if someone would make a pull request, I will merge it anyway. Thanks.
